version: '3.1'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - internal-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - internal-network
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

  api:
    image: 127.0.0.1:5000/nest-pret
    build: .
    restart: always
    command: npm run start:prod
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - api-server-data:/usr/src/app
    networks:
      - internal-network
    depends_on:
      - mongo

volumes:
  mongo-data:
  api-server-data:

networks:
  internal-network:
