version: '3.1'
name: 'nest-pret-e2e'

services:
  mongo:
    image: mongo
    volumes:
      - testmongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - testNetwork

  api:
    image: api
    build: .
    command: npm run test:e2e
    tty: true
    environment:
      - NODE_ENV=development
    networks:
      - testNetwork
    depends_on:
      - mongo

volumes:
  testmongodata:

networks:
  testNetwork:
