version: '3.1'
name: 'nest-pret-e2e'

services:
  mongo:
    image: mongo
    volumes:
      - testmongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - testNetwork

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - testNetwork
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

  api:
    image: api
    build: .
    command: npm run test:e2e
    tty: true
    environment:
      - NODE_ENV=development
    networks:
      - testNetwork
    depends_on:
      - mongo

volumes:
  testmongodata:

networks:
  testNetwork:
