version: '3.1'
name: 'nest-pret-e2e'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - internal-network

  api:
    image: api
    build: .
    command: npm run test:e2e -- ${TEST_ARG}
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - type: bind
      source: .
      target: /usr/src/app
    networks:
      - internal-network
    depends_on:
      - mongo

volumes:
  mongo-data:

networks:
  internal-network:
