version: '3.1'

services:
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - internalNetwork

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - internalNetwork
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

  api:
    image: api
    build: .
    restart: always
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    # volumes:
    #   - nestjsdata:/usr/src/app
    volumes:
    - type: bind
      source: .
      target: /usr/src/app
    networks:
      - internalNetwork
    depends_on:
      - mongo

volumes:
  mongodata:

networks:
  internalNetwork:
