version: '3.1'
name: 'nest-pret-dev'

services:
  mongo:
    image: mongo
    volumes:
      - nest-pret-dev-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - nest-pret-dev-internal-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8082
    networks:
      - nest-pret-dev-internal-network
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

  api:
    image: api
    build: .
    restart: always
    command: npm run start:dev
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3001
    volumes:
    - type: bind
      source: .
      target: /usr/src/app
    networks:
      - nest-pret-dev-internal-network
    depends_on:
      - mongo

volumes:
  nest-pret-dev-mongo-data:

networks:
  nest-pret-dev-internal-network:
